---
title: "Course Files"
output: github_document
---

<head>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>

Below you'll find the presentation files for the course and the exercises we'll do during the hands on sessions.

Note: You also have access to the source material at the [github repo](https://github.com/jbpost2/Basics-of-R-for-Data-Science-and-Statistics).

We've also included links to materials to go further learning R at the bottom of the page!

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
<h2 class="intro-text text-center">

<center>

<strong>Presentation Files</strong>

</center>

</h2>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
::: {.row}
::: {style="width: 50%;float: left;"}
    <center>
      <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/BasicsReadingData.html#1" target = "_blank">
          <i class="fa fa-list fa-stack-1x fa-inverse"></i></a>
      </span>
      <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/BasicsReadingData.html#1" target = "_blank">
        <h4 class="service-heading">R Basics & Reading Data</h4>
      </a>
      <p class="text-muted">
          <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/BasicsReadingData.pdf" target = "download">PDF version</a>
        </p>
        </center>
:::

::: {style="width: 50%;float: right;"}
    <center>
      <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/ManipulatingDataMarkdown.html#1" target = "_blank">
          <i class="fa fa-list fa-stack-1x fa-inverse"></i></a>
      </span>
      <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/ManipulatingDataMarkdown.html#1" target = "_blank">
        <h4 class="service-heading">Markdown & Manipulating Data</h4>
      </a>
      <p class="text-muted">
          <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/ManipulatingDataMarkdown.pdf" target = "download">PDF version</a> 
        </p>
    </center>
:::

::: {style="width: 50%;float: right;"}
    <center>
      <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/SummarizingData.html#1" target = "_blank">
          <i class="fa fa-list fa-stack-1x fa-inverse"></i></a>
      </span>
      <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/SummarizingData.html#1" target = "_blank">
        <h4 class="service-heading">Summarizing Data</h4>
      </a>
      <p class="text-muted">
          <a href="https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/slides/SummarizingData.pdf" target = "download">PDF version</a> 
        </p>
    </center>
:::
:::

::: {style="content: \"\";   clear: both;   display: table;"}
:::

It may help to have just the R code from the slides so you can easily run the code without typing it out. Below you'll find .R scripts with just the R code from the notes (notice that there is some extra stuff as we often use R code to bring in images and things like that).

-   <a href = "https://raw.githubusercontent.com/jbpost2/Basics-of-R-for-Data-Science-and-Statistics/main/slides/BasicsReadingData.R" target = "download"> R Basics & Reading Data R code</a>
-   <a href = "https://raw.githubusercontent.com/jbpost2/Basics-of-R-for-Data-Science-and-Statistics/main/slides/ManipulatingDataMarkdown.R" target = "download"> Markdown & Manipulating Data R code</a>
-   <a href = "https://raw.githubusercontent.com/jbpost2/Basics-of-R-for-Data-Science-and-Statistics/main/slides/SummarizingData.R" target = "download"> Summarizing Data R code</a>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
<h2 class="intro-text text-center">

<center>

<strong>Exercises</strong>

</center>

</h2>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
#### Exercise Sets

-   <a href = "https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_1_Exercises.html" target = "download"> Part 1 (RStudio IDE)</a>
-   <a href = "https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_2_Exercises.html" target = "download"> Part 2 (Data intake)</a>
-   <a href = "https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_3_Exercises.html" target = "download"> Part 3 (R Markdown)</a>\
-   <a href = "https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_4_Exercises.html" target = "download"> Part 4 (Data wrangling)</a>\
-   <a href = "https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_5_Exercises.html" target = "download"> Part 5 (Data visualization)</a>

#### Partial Solutions

-   Part 1 ([Rmd](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_1_Solutions.Rmd); [html](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_1_Solutions.html))
-   Part 2 ([Rmd](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_2_Solutions.Rmd); [html](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_2_Solutions.html))
-   Part 3 ([Rmd](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_3_Solutions.Rmd); [html](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_3_Solutions.html))
-   Part 4 ([Rmd](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_4_Solutions.Rmd); [html](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_4_Solutions.html))
-   Part 5 ([Rmd](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_5_Solutions.Rmd); [html](https://jbpost2.github.io/TeachingWithR/exercises/TeachingR_Part_5_Solutions.html))

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
<h2 class="intro-text text-center">

<center>

<strong>Learning Resources</strong>

</center>

</h2>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
#### Cheat Sheets

::: {.row}
::: {style="width: 33%;float: left;"}
    <center>
            <span class="fa-stack fa-4x">
                <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <a href="https://github.com/jbpost2/TeachingWithR/raw/main/cheatsheets/rstudio-ide.pdf" target="_blank">
                      <i class="fa fa-building fa-stack-1x fa-inverse"></i></a>
            </span>
            <h4 class="service-heading">
                    RStudio IDE
            </h4>
        </center>
:::

::: {style="width: 33%;float: left;"}
    <center>
        <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
                <a href="https://github.com/jbpost2/TeachingWithR/raw/main/cheatsheets/data-import.pdf" target="_blank">
              <i class="fa fa-book fa-stack-1x fa-inverse"></i></a>
        </span>
        <h4 class="service-heading">
                Data Import
        </h4>
    </center>
:::

::: {style="width: 33%;float: left;"}
    <center>
        <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
                <a href="https://github.com/jbpost2/TeachingWithR/raw/main/cheatsheets/rmarkdown-reference.pdf" target="_blank">
              <i class="fa fa-bell fa-stack-1x fa-inverse"></i></a>
        </span>
        <h4 class="service-heading">
                RMarkdown
        </h4>
    </center>
:::
:::

::: {style="content: \"\";   clear: both;   display: table;"}
:::

::: {.row}
::: {style="width: 33%;float: left;"}
    <center>
            <span class="fa-stack fa-4x">
                <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <a href="https://github.com/jbpost2/TeachingWithR/raw/main/cheatsheets/data-transformation.pdf" target="_blank">
                      <i class="fa fa-suitcase fa-stack-1x fa-inverse"></i></a>
            </span>
            <h4 class="service-heading">
                    Data Transformation
            </h4>
        </center>
:::

::: {style="width: 33%;float: left;"}
    <center>
        <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
                <a href="https://github.com/jbpost2/TeachingWithR/raw/main/cheatsheets/data-visualization-2.1.pdf" target="_blank">
              <i class="fa fa-anchor fa-stack-1x fa-inverse"></i></a>
        </span>
        <h4 class="service-heading">
                Data Visualization
        </h4>
    </center>
:::

::: {style="width: 33%;float: left;"}
    <center>
        <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
                <a href="https://github.com/jbpost2/TeachingWithR/raw/main/cheatsheets/shiny.pdf" target="_blank">
              <i class="fa fa-gears fa-stack-1x fa-inverse"></i></a>
        </span>
        <h4 class="service-heading">
                Shiny
        </h4>
    </center>
:::
:::

::: {style="content: \"\";   clear: both;   display: table;"}
:::

<hr>

#### Other Courses

Justin teaches the following three courses for [Data Matters](https://datamatters.org/), a week-long series of one and two-day courses aimed at students and professionals in business, research, and government. The material is open to anyone. Feel free to use these materials for any educational purpose!

<hr>

<h4>

<a href = "https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/" target = "_blank">Basics of R for Data Science and Statistics</a>

</h4>

This course covers the material in the first set of notes (R Basics, RMarkdown, & the tidyverse) in quite a bit more detail. All of the source materials are available on the corresponding github site as well.

<hr>

<h4>

<a href = "https://jbpost2.github.io/Improving-R-Programs/" target = "_blank">Improving R Programs</a>

</h4>

This course introduces common programming techniques that can improve the efficiency of your R programs. These techniques include the use of loops and vectorized functions to avoid repeated sections of code. To really take R programs to the next level, we see how to write custom functions that will help to streamline code.

<hr>

<h4>

<a href = "https://jbpost2.github.io/R-for-Automating-Workflow-Sharing-Work/" target = "_blank">R for Automating Workflow & Sharing Work</a>

</h4>

The course provides participants an introduction to utilizing R for writing reproducible reports and presentations that easily embed R output, using online repositories and version control software for collaboration, creation of basic websites using R, and the development of interactive dashboards and web applets.

I am in the process of updating this material. It will be ready by the first week of August (since that is when I have to teach it :).

<hr>

<h4>

<a href = "https://dtkaplan.github.io/DataComputingEbook/" target = "_blank">Data Computing eBook</a>

</h4>

This eBook (link)[<https://dtkaplan.github.io/DataComputingEbook/>] by Danny Kaplan and Matt Beckman is a free resource for an introduction to R course. The book has been used as a primary textbook for undergraduate courses that teach an introduction to R & `tidyverse` with no assumed prerequisites in statistics or programming. The book includes chapters devoted to basic RStudio IDE, data wrangling, visualization, and other topics useful for data processing & exploration.

<hr>

<br>

<a href = "https://jbpost2.github.io/TeachingWithR/"><button type="button">Workshop Home</button></a>
